name: Cron
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
  workflow_dispatch: { }

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: |
          ./target/release/apple-checker > /tmp/tmp.txt

          if grep GB /tmp/tmp.txt; then
            echo "Found an iPhone"
            cat /tmp/tmp.txt

            APP_TOKEN="$PUSHOVER_APP_TOKEN"
            USER_TOKEN="$PUSHOVER_USER_TOKEN"
            TITLE="Found an iPhone"
            MESSAGE="$(cat /tmp/tmp.txt)"
            curl 'https://api.pushover.net/1/messages.json' -X POST -d "token=$APP_TOKEN&user=$USER_TOKEN&message=\"$MESSAGE\"&title=\"$TITLE\""

            exit 1
          fi
        env:
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER_TOKEN: ${{ secrets.PUSHOVER_USER_TOKEN }}
